### ISSUE TITLE
'Line is Slightly off Axis' does not return host

### ISSUE THREAD

**Issue by MarkAckerley** [johnpierson/BangForDynamo#2]
Hi John,

Thanks for all your great work!

I don't think it's really a bug with Bang, I think it's probably a Dynamo issue, but perhaps you can help? Or suggest a workaround?

These guys had a similar issue? Depending on your Code? No resolution unfortunately... 

https://forums.autodesk.com/t5/revit-api-forum/revit-api-quot-get-warning-quot-method-does-not-get-parent/m-p/9201249/highlight/true#M43311

**Describe the bug**
When a Line is Slightly off Axis, the Revit warning dialogue returns both the line and the floor, but Bang is only giving me the line (which is difficult to relate back to the floor)
![image](https://user-images.githubusercontent.com/41670424/79311007-b6126400-7ef4-11ea-944f-de7ca75e5ad3.png)
![image](https://user-images.githubusercontent.com/41670424/79311025-bc084500-7ef4-11ea-8f0c-1ce889235cf1.png)

**Steps to Reproduce**
I made a floor with a line slightly off axis

**Expected behavior**
To have the line and the floor returned

**My setup**
- Operating System: Windows 10 Pro
- Dynamo version: 
![image](https://user-images.githubusercontent.com/41670424/79310844-7a779a00-7ef4-11ea-8d66-497aea33b24e.png)
- Bang! version: 
![image](https://user-images.githubusercontent.com/41670424/79310897-8e230080-7ef4-11ea-9181-441bbe483153.png)
- Revit version: ................
![image](https://user-images.githubusercontent.com/41670424/79310966-a72bb180-7ef4-11ea-8d2e-ef2822577be9.png)

Here's a test RVT renamed as a TXT to allow me to upload...
[test 2019.txt](https://github.com/johnpierson/BangForDynamo/files/4479778/test.2019.txt)

Cheers,

Mark

---
_This Github template was made possible thanks to [Andreas Dieckmann](https://github.com/andydandy74)_

**Comment by johnpierson** [comment]
hmmmmm. let me take a look. if it seems like a RevitAPI problem though, that's going to be weird.

**Comment by johnpierson** [comment]
So. I think I can modify my code to return the host if it is that warning specifically.
But not sure if I should since it is a hit or miss.

**Comment by MarkAckerley** [comment]
No worries, it’s your call :)

**Comment by johnpierson** [comment]
Something else I am seeing is in 2020, it is working.

**Comment by johnpierson** [comment]
Finally got it working in 2019. I had to do a weird workaround though. 
![image](https://user-images.githubusercontent.com/15744724/80151095-18b3d180-857f-11ea-9d99-cd3ce898e5e5.png)

**Comment by MarkAckerley** [comment]
Sweet, will have a play tomorrow!
